### PR TITLE
Simple refactoring

### LINKED ISSUE #54: Simple refactoring
### 1. Change `virtual` prefix to `override` suffix on overridden class methods
Functionally, there is no difference, but in general, the `override` keyword should be preferred because it enables extra compiler checks on your methods. For example, if there is a typo in the method name or the wrong return type, the compiler will complain about it. So, a method with declaration `virtual int getSize() const;` would become `int getSize() const override;`

### 2. Change `if`/`else` chains to `switch` statements
Again, there is no difference functionally, but switch statements can actually be a little faster if there are many cases, in addition to providing better readability. The one I spotted in particular was in the `spartan::LSM6DS33::writeReg` method, but if there are any others, change those too!

### PR DESCRIPTION
**Pull request by grantKinsley**
Closes #54 

1. Changed "virtual" to "override" in overridden methods for sub-classes under the "PacketType" and "Sensor" classes.
2.  Changed if/else block to a switch block in the spartan::LSM6DS33::writeReg method. I couldn't find any other huge if/else blocks that required changing.

### CODE REVIEW

File: Software/src/sensors/lsm6ds33.cpp [hunk 1]
```diff
@@ -26,26 +26,30 @@ bool spartan::LSM6DS33::writeReg(uint8_t* buffer, unsigned short size) {
...
+    case mraa::ERROR_NO_DATA_AVAILABLE:
+        std::cerr << "ERROR_NO_DATA_AVAILABLE" << std::endl; break;
+    case mraa::ERROR_INVALID_PLATFORM:
+        std::cerr << "ERROR_INVALID_PLATFORM" << std::endl; break;
+    case mraa::ERROR_PLATFORM_NOT_INITIALISED:
+        std::cerr << "ERROR_PLATFORM_NOT_INITIALISED" << std::endl; break;
+    case mraa::ERROR_UNSPECIFIED:
+        std::cerr << "ERROR_UNSPECIFIED" << std::endl; break;
+    default: break;
+    }
```
Comment (harrisonCassar) [inline Software/src/sensors/lsm6ds33.cpp]: For the sake of readability and style, can each case have its body's statements on different lines (i.e. `break` statements on a separate line)? This helps a user to see which cases are fall-through or not (in this case, they're all not, but we'll use this stylistic choice anyway). See [Oracle Docs](https://www.oracle.com/java/technologies/javase/codeconventions-statements.html#468) for more information.

**Review by harrisonCassar — CHANGES_REQUESTED** [review]
Looks great! One small stylistic fix, and then it should be ready to merge!

File: Software/src/sensors/lsm6ds33.cpp (hunk 1 above)
Comment (harrisonCassar) [reply Software/src/sensors/lsm6ds33.cpp]: Also, for the first case for `mraa::SUCCESS`, since we `return true`, we shouldn't include a `break` statement. This does contradict slightly with what I put above^ but since its only one line, we should be fine.

**Review by harrisonCassar — APPROVED** [review]

**Review by tiffany1618 — APPROVED** [review]
Looks good!
